### ISSUE TITLE
less frequent calls to the repo label management

### ISSUE THREAD

**Issue by twk3** [actualbudget/actual-gh-bot#11]
Currently we list and sync all labels (for the repo) to ensure our colors and descriptiosn match on all of our main listeners.

This probably is more often than we need. We could instead do this only on:

`installation,installation_repositories,installation_target` events. So they only happen when the bot is added/modified for a repo. This might be less frequent than we would like, but should save us on resources and api calls.

**Comment by matt-fidd** [comment]
Yes, this would probably be sufficient. The reason I put it somewhere more frequent is to cover the case where a new label is added, but permissions wouldn't change and the bot wouldn't be reinstalled.

I imagine this is probably not worth worrying about as it could only happen once or twice (or never!) in the bot's lifetime.
