### ISSUE TITLE
rollout to actual repos

### ISSUE THREAD

**Issue by twk3** [actualbudget/actual-gh-bot#12]
- [x] docs
- [x] actual-server
- [x] actual

Rolled out to docs right away, because it hasn't had a workflow added since traffico stopped working.

For the other two, we will want to drop the workflow at the same time.

**Comment by twk3** [comment]
rolled out to actual-server today

**Comment by twk3** [comment]
Rolled out to the main actual project today

will close this issue tomorrow if we don't feel the need to rollback

**Comment by twk3** [comment]
Counting this as complete. Bot has taken over :)

**Comment by matt-fidd** [comment]
Woo! Thanks for all of your help :)
