### ISSUE TITLE
Only Approve with maintainer approval

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual-gh-bot#18]
In not sure if I would like this yet or not.

Would it be possible to only give the approved label if there has been a maintainer approval?

**Comment by matt-fidd** [comment]
It looks like a trivial change to limit the approved label to only set if a "collaborator" approved

**Comment by youngcw** [comment]
Those with push access could work.

**Comment by matt-fidd** [comment]
I think it makes more sense. The PR can't be merged until a maintainer approves it, so is it really "approved" until they do?

**Comment by youngcw** [comment]
We should run it by the others first, but I think it would help keep things more consistent and "as expected".

**Comment by matt-fidd** [comment]
@youngcw have you had any more thoughts on this?

**Comment by youngcw** [comment]
Only those with push access makes sense to me to label as approved.  If we really want to know if someone else chimed in, its in the full breakdown, or the fine print of the PR.

**Comment by matt-fidd** [comment]
What do you reckon to the changes requested label, should that apply on a change requested by a non-maintainer or not?

**Comment by youngcw** [comment]
I think it would be fine for the changes requested label too.  I think the primary goal of the labels is to help direct the attention of the maintainers, so having the labels show maintainer interaction is probably more useful than showing all interactions.  The PR author will still see all comments and requests regardless, so no issue there.
