### ISSUE TITLE
The "Changes Requested" label seems to never go away

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual-gh-bot#19]
What are the triggers to remove the "Changes Requested" label?  It seems to just sit currently.  I don't know if there ever will be a good way for the bot to confirm if the requested changes actually happen, but maybe it could go away after some amount of commits or something?  Currently it makes some PRs look like nothing has happened even if there have been updates.

**Comment by matt-fidd** [comment]
Looking at the trafico implementation I think it dismissed all reviews on any push (it only ever considered a reviews against the most recent commit). This isn't perfect either but it would probably cover a bit better? It would result in any push reverting the label back to "ready for review". And covers the case where a stale review is dismissed.

At the moment the changes requested label will only go away once all users that request changes on the most recent commit submit an approving review. 

There must be a nice way to check if the requested changes are outdated but it's not coming to me. Ideally we wouldn't want to remove the changes requested label until either that review is dismissed or the changes are made.

**Comment by matt-fidd** [comment]
Sorry, reread now - trafico uses pull_request_review.dismissed and we should too.

**Comment by matt-fidd** [comment]
Sorry for any confusion if you've seen my edits. I was right the first time. Trafico updates the status on every push.
