### ISSUE TITLE
Bug? User error? Tags - Removing changes requested and adding RFR when syncing branch with upstream

### ISSUE THREAD

**Issue by wdpk** [actualbudget/actual-gh-bot#22]
I think this is either my fault for an unconventional workflow, or perhaps a bug in the tag logic.

First the broad situation:
I have a PR, I get some reviews, before I can address those reviews, some changes are pushed to upstream branch.

As I'm going through my reviews, I sync with upstream. Because i'm using the button on the github.com interface, this also pushes a commit to the repository. [time 0]

I then make some changes that incorporate the comments, and push that to my repository the PR is based on. [time 1]

The bot seems to remove the Changes Requested tag at time 0, but I think it should only be happening at time 1?

Or, if I was using an IDE, syncing with main wouldn't cause a commit and this wouldn't be a problem, so this is really just because I'm using the web interface only?

**Comment by matt-fidd** [comment]
I haven't hit this as you say because I do my syncs and commits then push after. 

I believe this should have been the same with the Trafico implementation looking at the code though. Did you have the same issue before?

The ideal solution would be to actually check if the requested changes had been made, or acknowledged, discussed and dismissed. This feels computationally expensive though.

**Comment by twk3** [comment]
It really depends on the context of the review. If the review comment says "please update this from master to bring in xyz", :shrug: 

Though one thought, is that we are listing it as ready for review even though github still has the some reviews listed as changes requested. Can fork communinity users re-request review or remove reviewers? If so then maybe we leave it as changes requested whenever github reviews say there are still changes requested.

**Comment by wdpk** [comment]
> I haven't hit this because, as you say, I do my rebasing and commits locally then push after.
> 
> I believe this should have been the same with the Trafico implementation looking at the code though. Did you have the same issue before?
> 
> The ideal solution would be to actually check if the requested changes had been made, or acknowledged, discussed and dismissed. This feels computationally expensive though.

Unfortunately, I don't think I had a PR open with the Trafico bot. I'm not sure though. New to contributing (if that wasn't clearly evidenced by me using the github.com interface). 

When I have been getting reviews, my general workflow has been to;
1) respond, basically acknowledging the review contents and kind of stating my intent to do [x] to 'fix' this comment. so that if i'm wildly off-base and my solution sounds like i'm missing the point, why i went where I did with the code can at least make more sense in context.
2) incorporate the changes into the code, push the fix
3) mark the review comment as 'resolved'
4) as the bot as already marked the pr as ready for review, i do nothing else.



> It really depends on the context of the review. If the review comment says "please update this from master to bring in xyz", 🤷
> 
> Though one thought, is that we are listing it as ready for review even though github still has the some reviews listed as changes requested. Can fork communinity users re-request review or remove reviewers? If so then maybe we leave it as changes requested whenever github reviews say there are still changes requested.

I can't seem to remove reviewers, even for non-maintainer reviewers. I can 're-request review' though. I didn't click it (until just now, for testing) because it felt kind of rude if it was going to send a reviewer a push notification or something? if clicking it is ok or desirable as a way to say "I'm ready, i have finished all my fixes, and addressed the build/lint issues" then I think as long as some part of the documentation made it clear that is the right way to get the "Ready for Review" tag back, it could be a good way to handle the automation I think? Or if that is the only way to get the right tag, people might be more likely to click it. I felt no "need" to click request re-review, because the PR had the RFR tag. If I had done everything to be *ready for review* but still had the "Changes requested" tag, I would have likely tried clicking the other interactable elements, like "resolve" for the comment threads, and ultimately the "request" button.

"requests review" seems to be a tracked action that the bot could presumably interact with?

e.g.;

@[wdpk](https://github.com/wdpk) wdpk requested a review from [twk3](https://github.com/twk3) [2 minutes ago](https://github.com/actualbudget/actual/pull/2973#event-13547302155)
