### ISSUE TITLE
feat: gate the CI check behind a feature flag

### ISSUE THREAD

**Issue by twk3** [actualbudget/actual-gh-bot#3]
The CI failing labels are a great idea, but I think we should make it optional for the first deployment, so we can get the rest up and running, then introduce the CI change. 

- [ ] Gate the Suite check behind an environment variable for now

I believe there might be some current edge case issues due to the fact that it mostly just toggles between ci failure and ready for review. But we can look at those after the rest is up and running.

**Comment by twk3** [comment]
What would be better is if we could have it gated on some config in the repo. That way I can turn it on for a single one of our repos that has less contributions while we test it.

**Comment by matt-fidd** [comment]
Looks like this is fairly straightforward, Probot can take config from target repos via a .yml file in the `.github` dir.

Picturing something like:
`actual/.github/actual-gh-bot.yml`
```yml
features:
  enableFailingCI: false
```

I tested the failingCI pretty thoroughly with a couple of test suites but actual's suites are pretty convoluted, it could be that it does things I wasn't expecting!
